# Generated by Django 4.2 on 2023-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('negativo', models.BooleanField()),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
